# Generated by Django 5.0.6 on 2024-07-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.AddField(
            model_name='product',
            name='products_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
