# Generated by Django 5.0.6 on 2024-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_review_stars_product_products_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='products_count',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
